# fly.toml app configuration file generated for proto2 on 2023-06-04T17:43:07-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "proto2"
primary_region = "ams"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[[services]]
  protocol = "tcp"
  internal_port = 10000

  [[services.ports]]
    port = 10000
